In [1]:
import numpy as np

In [4]:
a = np.arange(24).reshape((6,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
%%time
a = np.arange(100_000)

CPU times: user 207 µs, sys: 114 µs, total: 321 µs
Wall time: 215 µs


In [10]:
%%time
abs(a)

CPU times: user 1.01 ms, sys: 1.37 ms, total: 2.38 ms
Wall time: 1.79 ms


array([    0,     1,     2, ..., 99997, 99998, 99999])

In [11]:
%%time
np.absolute(a)

CPU times: user 709 µs, sys: 536 µs, total: 1.25 ms
Wall time: 618 µs


array([    0,     1,     2, ..., 99997, 99998, 99999])