In [1]:
import numpy as np

In [2]:
a = [1,2,3]
b = [4,5,6]

In [3]:
a + b

[1, 2, 3, 4, 5, 6]

In [4]:
result = []
for i, j in zip(a,b):
    result.append(i+j)
result

[5, 7, 9]

In [5]:
arr_a = np.array(a)
arr_b = np.array(b)

In [6]:
arr_a + arr_b

array([5, 7, 9])

In [7]:
type(arr_a)



numpy.ndarray

In [8]:
arr_a.size

3

In [9]:
arr_a.shape

(3,)

In [10]:
arr_a.ndim

1

In [14]:
np.sin(arr_a)

array([0.84147098, 0.90929743, 0.14112001])

In [15]:
np.abs(arr_a)

array([1, 2, 3])

In [16]:
arr_a * 3


array([3, 6, 9])

In [17]:
arr_b // 3

array([1, 1, 2])

In [19]:
arr_b % 3

array([1, 2, 0])

In [20]:
arr_b

array([4, 5, 6])

In [21]:
py_list_c = [1, 'a', 1.0, [4,5,6]]

In [22]:
py_list_c.append(90)
py_list_c

[1, 'a', 1.0, [4, 5, 6], 90]

In [23]:
arr_a

array([1, 2, 3])

In [24]:
arr_a.dtype

dtype('int64')

In [25]:
arr_c = np.array([1.0, 3.4, 5.6])

In [26]:
arr_c.dtype

dtype('float64')

In [27]:
arr_a

array([1, 2, 3])

In [28]:
arr_a[0]

1

In [29]:
arr_a[1]

2

In [30]:
arr_a[2]

3

In [31]:
arr_a[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [32]:
arr_a

array([1, 2, 3])

In [33]:
arr_a[2] = 99
arr_a

array([ 1,  2, 99])

In [34]:
arr_a.dtype

dtype('int64')

In [35]:
arr_a[1] = 5.4

In [36]:
arr_a

array([ 1,  5, 99])

In [37]:
arr_c.dtype

dtype('float64')

In [38]:
arr_c

array([1. , 3.4, 5.6])

In [39]:
arr_c[1] = 88

In [40]:
arr_c

array([ 1. , 88. ,  5.6])

In [41]:
arr_c[1] = 'a'

ValueError: could not convert string to float: 'a'

In [42]:
arr_c

array([ 1. , 88. ,  5.6])

In [43]:
arr_c.itemsize

8

In [45]:
arr_d = np.array([[1,2,3],[4,5,6]])
arr_d

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr_d.shape

(2, 3)

In [48]:
arr_d[0]

array([1, 2, 3])

In [49]:
arr_d[0][1]

2

In [50]:
arr_d[0, 1]

2

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
arr_f = np.arange(10)
arr_f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr_f[3]

3

In [55]:
len(arr_f)

10

In [56]:
arr_f[9]

9

In [57]:
arr_f[-1]

9

In [58]:
arr_f[-3]

7

In [59]:
arr_f[-8]

2

In [ ]:
# slicing
# [start: end: step]
# end is not included 


In [60]:
arr_f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr_f[0: 7: 1]

array([0, 1, 2, 3, 4, 5, 6])

In [62]:
arr_f[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [63]:
arr_f[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [64]:
arr_f[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr_f[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [66]:
arr_f[::2]

array([0, 2, 4, 6, 8])

In [67]:
arr_f[1::2]

array([1, 3, 5, 7, 9])

In [68]:
arr_g = arr_f[1::2]
arr_g

array([1, 3, 5, 7, 9])

In [69]:
arr_g[2] = 99
arr_g

array([ 1,  3, 99,  7,  9])

In [70]:
arr_f

array([ 0,  1,  2,  3,  4, 99,  6,  7,  8,  9])

In [71]:
arr_h = arr_f[1::2].copy()

In [72]:
arr_h

array([ 1,  3, 99,  7,  9])

In [73]:
arr_h[2] = 888
arr_h

array([  1,   3, 888,   7,   9])

In [74]:
arr_f

array([ 0,  1,  2,  3,  4, 99,  6,  7,  8,  9])

In [76]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
a[::,::]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [83]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [84]:
a.shape

(25,)

In [86]:
a = a.reshape(5,5)

In [87]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
red = a[:, 1::2]
red

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [95]:
yellow = a[-1]
yellow

array([20, 21, 22, 23, 24])

In [100]:
a[1::2, 0:3:2]

array([[ 5,  7],
       [15, 17]])

In [103]:
arr_a = np.arange(10) + 5
arr_a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [104]:
arr_a[1::2]

array([ 6,  8, 10, 12, 14])

In [105]:
arr_a[1::2] = [40, 41, 42, 43, 44]

In [106]:
arr_a

array([ 5, 40,  7, 41,  9, 42, 11, 43, 13, 44])

In [107]:
arr_a[1::2] = [40, 41, 42, 43]

ValueError: could not broadcast input array from shape (4,) into shape (5,)

In [108]:
arr_a[1::2] = 99
arr_a

array([ 5, 99,  7, 99,  9, 99, 11, 99, 13, 99])

In [109]:
b = arr_a[::2]
b

array([ 5,  7,  9, 11, 13])

In [110]:
b[3] = 55

In [111]:
arr_a

array([ 5, 99,  7, 99,  9, 99, 55, 99, 13, 99])

In [113]:
np.shares_memory(arr_a, b)

True

In [114]:
# slices [start:stop:step]

In [115]:
# fancy indexing
# 1. give indexes directly
# 2. build a boolean mask

In [117]:
arr_a = np.arange(10) + 5
arr_a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [118]:
# give indexes directly
# indexes: 2, 3, 7, 8 
arr_a[[2, 3, 7, 8]]

array([ 7,  8, 12, 13])

In [119]:
arr_a[[2, 3, 7, -2]]

array([ 7,  8, 12, 13])

In [120]:
arr_a[[2, 3, -2, 7]]

array([ 7,  8, 13, 12])

In [121]:
arr_a[[2, 3, -2, 7, 2, 3]]

array([ 7,  8, 13, 12,  7,  8])

In [122]:
idx_list = [1, 4, 2, -5]
arr_a[idx_list]

array([ 6,  9,  7, 10])

In [123]:
# indexing with booleans
arr_a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [126]:
bool_idx = [True, True, False, True, False, False, True, True, False, False]
len(bool_idx), len(arr_a)

(10, 10)

In [127]:
arr_a[bool_idx]

array([ 5,  6,  8, 11, 12])

In [128]:
arr_a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [129]:
arr_a % 3

array([2, 0, 1, 2, 0, 1, 2, 0, 1, 2])

In [130]:
arr_a % 3 == 0

array([False,  True, False, False,  True, False, False,  True, False,
       False])

In [132]:
div_3_idx = (arr_a % 3 == 0)
div_3_idx

array([False,  True, False, False,  True, False, False,  True, False,
       False])

In [134]:
# mask
arr_a[div_3_idx]

array([ 6,  9, 12])

In [135]:
arr_a[arr_a % 3 == 0]

array([ 6,  9, 12])

In [139]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [140]:
# pick up 1, 7, 16, 23
rows = [0, 1, 3, 4]
cols = [1, 2, 1, 3]

In [141]:
a[rows, cols]

array([ 1,  7, 16, 23])

In [142]:
list(zip(rows, cols))

[(0, 1), (1, 2), (3, 1), (4, 3)]

In [143]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [144]:
rows = [0, 1, 2, 3]
cols = [3, 1, 0, 4]
list(zip(rows, cols))

[(0, 3), (1, 1), (2, 0), (3, 4)]

In [145]:
a[rows, cols]

array([ 3,  6, 10, 19])

In [146]:
rows = [0, 2, 1, 3]
cols = [3, 1, 0, 4]
list(zip(rows, cols))

[(0, 3), (2, 1), (1, 0), (3, 4)]

In [147]:
a[rows, cols]

array([ 3, 11,  5, 19])

In [148]:
a % 3 == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [149]:
a[a % 3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [150]:
np.zeros(3)

array([0., 0., 0.])

In [151]:
np.zeros((1, 3))

array([[0., 0., 0.]])

In [153]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [154]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [155]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [157]:
a = np.ones((3, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [158]:
a.dtype

dtype('float64')

In [160]:
np.ones((3,5), dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [162]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [164]:
np.linspace(1,10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [165]:
np.logspace(1, 10, 5)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [177]:
rng = np.random.default_rng(seed=42)

In [178]:
rng.integers(5, size=5)

array([0, 3, 3, 2, 2])

In [179]:
rng.integers(5, size=5)


array([4, 0, 3, 1, 0])

In [180]:
rng.integers(5, size=5)


array([2, 4, 3, 3, 3])

In [183]:
rng.uniform(size=(5,6))

array([[0.12811363, 0.45038594, 0.37079802, 0.92676499, 0.64386512,
        0.82276161],
       [0.4434142 , 0.22723872, 0.55458479, 0.06381726, 0.82763117,
        0.6316644 ],
       [0.75808774, 0.35452597, 0.97069802, 0.89312112, 0.7783835 ,
        0.19463871],
       [0.466721  , 0.04380377, 0.15428949, 0.68304895, 0.74476216,
        0.96750973],
       [0.32582536, 0.37045971, 0.46955581, 0.18947136, 0.12992151,
        0.47570493]])

In [185]:
rng.standard_normal(size=(2,3))

array([[-0.82448122,  0.65059279,  0.74325417],
       [ 0.54315427, -0.66550971,  0.23216132]])

In [189]:
x = np.linspace(-10.0, 10.0, num=8)
x

array([-10.        ,  -7.14285714,  -4.28571429,  -1.42857143,
         1.42857143,   4.28571429,   7.14285714,  10.        ])

In [191]:
np.pi /10

0.3141592653589793

In [194]:
x = x * np.pi/10

In [195]:
x

array([-0.98696044, -0.70497174, -0.42298305, -0.14099435,  0.14099435,
        0.42298305,  0.70497174,  0.98696044])

In [196]:
y = np.cos(x)

In [197]:
y

array([0.55122847, 0.76162986, 0.91186851, 0.99007675, 0.99007675,
       0.91186851, 0.76162986, 0.55122847])

In [201]:
%ls exercises/load_text/float_data.txt

exercises/load_text/float_data.txt


In [203]:
arr_float_data = np.loadtxt('exercises/load_text/float_data.txt')

In [204]:
arr_float_data

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [205]:
arr_float_data.shape

(2, 4)

In [206]:
%ls exercises/load_text/float_data_with_header.txt

exercises/load_text/float_data_with_header.txt


In [211]:
np.loadtxt('exercises/load_text/float_data_with_header.txt', skiprows=1)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [213]:
%ls exercises/load_text/complex_data_file.txt

exercises/load_text/complex_data_file.txt


In [221]:
arr_from_text = np.loadtxt(
    'exercises/load_text/complex_data_file.txt', 
    skiprows=1, comments='%', delimiter=',',
    usecols=[0,1,2,4]
)
arr_from_text

array([[1.00e+00, 1.00e+00, 2.00e+03, 3.00e+01],
       [2.00e+00, 1.00e+00, 2.00e+03, 4.10e+01],
       [4.00e+00, 1.00e+00, 2.00e+03, 5.50e+01],
       [5.00e+00, 1.00e+00, 2.00e+03, 7.80e+01],
       [6.00e+00, 1.00e+00, 2.00e+03, 1.34e+02],
       [7.00e+00, 1.00e+00, 2.00e+03, 4.20e+01]])

In [223]:
np.save('arr_from_text', arr_from_text)

In [225]:
npy_load_arr = np.load('arr_from_text.npy')

In [226]:
npy_load_arr

array([[1.00e+00, 1.00e+00, 2.00e+03, 3.00e+01],
       [2.00e+00, 1.00e+00, 2.00e+03, 4.10e+01],
       [4.00e+00, 1.00e+00, 2.00e+03, 5.50e+01],
       [5.00e+00, 1.00e+00, 2.00e+03, 7.80e+01],
       [6.00e+00, 1.00e+00, 2.00e+03, 1.34e+02],
       [7.00e+00, 1.00e+00, 2.00e+03, 4.20e+01]])

In [227]:
arr_a = np.array([0,1,2,3])
arr_b = np.array([5,6,7,8])

In [228]:
arr_a.shape, arr_b.shape

((4,), (4,))

In [229]:
arr_a + arr_b

array([ 5,  7,  9, 11])

In [230]:
arr_a * arr_b

array([ 0,  6, 14, 24])

In [231]:
arr_c = np.array([3,4,5])

In [232]:
arr_a + arr_c

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [233]:
arr_a  + 10

array([10, 11, 12, 13])

In [234]:
arr_a + [10]

array([10, 11, 12, 13])

In [235]:
arr_a + np.array([10])

array([10, 11, 12, 13])

In [236]:
arr_a.sum()

6

In [237]:
arr_d = np.arange(24).reshape(4,6)
arr_d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [239]:
arr_d.shape

(4, 6)

In [240]:
arr_d.sum()

276

In [245]:
np.sum(arr_d, axis=0)

array([36, 40, 44, 48, 52, 56])

In [246]:
np.sum(arr_d, axis=1)

array([ 15,  51,  87, 123])

In [248]:
arr_d.sum(axis=1)

array([ 15,  51,  87, 123])

In [251]:
arr_d.prod()

0

In [252]:
arr_d.min()

0

In [253]:
arr_d.max()

23

In [254]:
arr_d.max(axis=1)

array([ 5, 11, 17, 23])

In [255]:
arr_d.mean(axis=1)

array([ 2.5,  8.5, 14.5, 20.5])

In [256]:
arr_a.argmax()

3

In [257]:
arr_a

array([0, 1, 2, 3])

In [258]:
arr_a.argmin()

0

In [259]:
arr_d.shape

(4, 6)

In [260]:
arr_d.argmin()

0

In [261]:
arr_d.min()

0

In [262]:
arr_d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [263]:
min_pos = arr_d.argmin()
min_pos

0

In [264]:
arr_d[min_pos]

array([0, 1, 2, 3, 4, 5])

In [265]:
np.unravel_index(min_pos, arr_d.shape)

(0, 0)

In [274]:
row, col = np.where(arr_d==20)

In [273]:
arr_d == 20

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False]])

In [275]:
arr_d[row, col]

array([20])

In [276]:
positives = np.arange(1,6)
positives 

array([1, 2, 3, 4, 5])

In [277]:
negatives = -positives
negatives

array([-1, -2, -3, -4, -5])

In [278]:
mask = [True, True, False, False, True]

In [279]:
np.where(mask, positives, negatives)

array([ 1,  2, -3, -4,  5])

In [280]:
np.where(mask, positives, 99)

array([ 1,  2, 99, 99,  5])

In [282]:
a = np.arange(-15, 15).reshape(5,6) ** 2
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]])

In [283]:
a.max()

225

In [284]:
a.max(axis=1)

array([225,  81,   9,  64, 196])

In [285]:
a.mean(axis=0)

array([81., 76., 73., 72., 73., 76.])

In [286]:
a.min()

0

In [287]:
a.argmin()

15

In [288]:
a.shape

(5, 6)

In [289]:
np.unravel_index(a.argmin(), a.shape)

(2, 3)

In [291]:
np.where(a == a.min())

(array([2]), array([3]))

In [293]:
a.min(axis=1).argmin()

2

In [294]:
a.min(axis=0).argmin()

3

In [295]:
a = np.ones((3,5))
b = np.ones((5,))

In [296]:
a


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [297]:
b

array([1., 1., 1., 1., 1.])

In [298]:
a + b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [299]:
a.shape

(3, 5)

In [300]:
b.shape

(5,)

In [301]:
c = np.ones((3,))

In [302]:
a + c

ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

In [303]:
b

array([1., 1., 1., 1., 1.])

In [304]:
b.shape

(5,)

In [305]:
b.reshape(1,5)

array([[1., 1., 1., 1., 1.]])

In [306]:
b[np.newaxis, :]

array([[1., 1., 1., 1., 1.]])

In [308]:
b.data